name: Reusable Build and Test UI Docker Project

on:
  workflow_call:
    inputs:
      working_directory_path:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      UI_BackEnd_API_URL:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: CI=true npm run test:ci
        continue-on-error: true
        timeout-minutes: 10

      - name: Build the Docker image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ inputs.UI_BackEnd_API_URL }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ inputs.repository_name }}:${{ github.run_number }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ inputs.repository_name }}:latest .

      - name: Log in to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ inputs.repository_name }}:${{ github.run_number }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ inputs.repository_name }}:latest
